services:
  - type: web
    name: face-search-pro
    runtime: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    disk:
      name: face-index
      mountPath: /app/data
      sizeGB: 10
